<img src="../img/logoAIEP.jpg" alt="Logo de AIEP" width="300">

Importar Pandas

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

Se importa Dataset para la creacion del dataframe

In [2]:
df = pd.read_csv("../dataset/taco_sales_2024-2025.csv")

In [8]:
df.head(10)

,Order ID,Restaurant Name,Location,Order Time,Delivery Time,Delivery Duration (min),Taco Size,Taco Type,Toppings Count,Distance (km),Price ($),Tip ($),Weekend Order
0,770487,El Taco Loco,New York,01-08-2024 14:55,01-08-2024 15:36,41,Regular,Chicken Taco,5,3.01,9.25,2.22,False
1,671858,El Taco Loco,San Antonio,23-11-2024 17:11,23-11-2024 17:25,14,Regular,Beef Taco,1,6.20,4.25,3.01,True
2,688508,Taco Haven,Austin,21-11-2024 20:24,21-11-2024 21:02,38,Large,Pork Taco,2,20.33,7.00,0.02,False
3,944962,Spicy Taco House,Dallas,21-09-2024 06:43,21-09-2024 07:28,45,Regular,Chicken Taco,2,3.00,5.50,1.90,True
4,476417,Casa del Taco,San Antonio,24-07-2024 11:01,24-07-2024 11:16,15,Large,Pork Taco,0,24.34,4.50,1.14,False
5,678856,Urban Tacos,San Antonio,07-10-2024 21:21,07-10-2024 22:44,83,Regular,Beef Taco,0,16.70,3.00,2.32,False
6,183667,Taco Haven,Los Angeles,22-10-2024 06:03,22-10-2024 06:48,45,Large,Veggie Taco,1,9.57,5.75,0.63,False
7,379946,El Taco Loco,San Antonio,08-05-2025 04:51,08-05-2025 05:22,31,Regular,Chicken Taco,3,9.80,6.75,2.97,False
8,771088,The Taco Stand,Houston,08-09-2024 21:04,08-09-2024 21:21,17,Regular,Beef Taco,2,10.33,5.50,0.33,True
9,694731,Casa del Taco,Houston,24-05-2025 02:15,24-05-2025 03:28,73,Large,Fish Taco,1,6.99,5.75,1.23,True